name: 💡 Запрос функции
about: Предложить функцию, апплет или сценарий расписания
body:
  - type: textarea
    id: problem
    attributes:
      label: Рабочая задача
    validations:
      required: true
  - type: textarea
    id: flow
    attributes:
      label: Ожидаемый flow
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Обезличенный пример
