import { calendarKey } from './calendar.js';
import { lessonKey } from './model.js';
const val=(matrix,r,c)=>matrix?.[r]?.[c];const txt=(v)=>String(v??'').trim();const lower=(v)=>txt(v).toLocaleLowerCase('ru-RU');
export function detectProfile(matrix){let weeksRow=-1,weekStartCol=-1,legendRow=-1;for(let r=0;r<Math.min(matrix.length,30);r++){for(let c=0;c<Math.min(matrix[r]?.length||0,20);c++){const x=lower(val(matrix,r,c));if(weeksRow<0&&x.includes('уч.')&&x.includes('недел'))weeksRow=r;if(legendRow<0&&x.startsWith('обозн'))legendRow=r;}}
if(weeksRow>=0){for(let c=0;c<(matrix[weeksRow]?.length||0);c++){if(Number(val(matrix,weeksRow,c))===1){weekStartCol=c;break;}}}
return {weeksRow,weekStartCol,monthsRow:weeksRow+1,gridStartRow:weeksRow+3,legendRow,days:6,pairs:4,rowsPerDay:13,rowsPerPair:3,codeOffset:0,subjectOffset:1,roomOffset:2,dateOffset:-1,abbrCol:0,lecturerCol:9,otherCol:13};}
export function validateProfile(p){const errors=[];for(const k of ['weeksRow','weekStartCol','gridStartRow'])if(Number(p[k])<0)errors.push(`Не определён ${k}`);if(!Number(p.days)||!Number(p.pairs))errors.push('Некорректные дни или пары');return errors;}
function lessonType(code){const p=txt(code).split('/')[0];return p||'П';}
export function parseScheduleMatrix(matrix,{sourceId='SRC',group='Группа',profile=detectProfile(matrix),calendar=[]}={}){const errors=validateProfile(profile);if(errors.length)return {lessons:[],legend:[],warnings:errors,profile};const weekCols=[];for(let c=profile.weekStartCol;c<(matrix[profile.weeksRow]?.length||0);c++){const w=Number(val(matrix,profile.weeksRow,c));if(Number.isFinite(w)&&w>0)weekCols.push([c,w]);}
const cal=new Map(calendar.map(x=>[calendarKey(x.week,x.day),x]));const days=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];const lessons=[],warnings=[];for(let di=0;di<profile.days;di++){const base=profile.gridStartRow+di*profile.rowsPerDay;for(let pair=1;pair<=profile.pairs;pair++){const row=base+(pair-1)*profile.rowsPerPair;for(const [c,week] of weekCols){const code=txt(val(matrix,row+profile.codeOffset,c)),subject=txt(val(matrix,row+profile.subjectOffset,c)),room=txt(val(matrix,row+profile.roomOffset,c));if(!code&&!subject)continue;const day=days[di],calRow=cal.get(calendarKey(week,day));const lesson={sourceId,group,week,dayOfWeek:day,pairNumber:pair,date:calRow?.date||'',dayNumber:calRow?.dayOfMonth||'',month:calRow?.month||'',code,lessonType:lessonType(code),subject,room,cellAddress:`R${row+1}C${c+1}`,status:'Готово'};lesson.lessonId=lessonKey(lesson);lessons.push(lesson);}}}
const legend=[];if(profile.legendRow>=0){for(let r=profile.legendRow+3;r<matrix.length;r++){const subject=txt(val(matrix,r,profile.abbrCol));if(!subject)break;const lecture=txt(val(matrix,r,profile.lecturerCol)),others=txt(val(matrix,r,profile.otherCol));if(lecture)legend.push({sourceId,subject,lessonType:'Л',rawTeachers:lecture});for(const t of ['П','С','У','ЛР','ЗО','Экз'])if(others)legend.push({sourceId,subject,lessonType:t,rawTeachers:others});}}
return {lessons,legend,warnings,profile};}
